[System]
# Example configuration for running an ONNX Green-on-Green model
algorithm = gog
input_file_or_directory =
relay_num = 4
actuation_duration = 0.15
delay = 0

[Camera]
resolution_width = 416
resolution_height = 320
exp_compensation = -2

[GreenOnGreen]
# Path to a directory containing models or a single .onnx file
model_path = models
confidence = 0.5
class_filter_id = None

[GreenOnBrown]
exg_min = 25
exg_max = 200
hue_min = 41
hue_max = 80
saturation_min = 52
saturation_max = 218
brightness_min = 62
brightness_max = 188
min_detection_area = 20
invert_hue = False

[DataCollection]
sample_images = False
sample_method = whole
sample_frequency = 30
save_directory = /media/owl/SanDisk
disable_detection = False
log_fps = False
camera_name = cam1

[Relays]
0 = 13
1 = 15
2 = 16
3 = 18

